### ISSUE TITLE
Extra Quotation making metasploit failing to take the CVE from Searchsploit

### ISSUE THREAD

**Issue by phoenixml** [pablosnt/rekono#172]
**Describe the bug**
Metasploit completed without a finding

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Start a new process'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14360476/221339580-e1508a53-b499-41d7-b0f4-3c88adbd7ba8.png)

**Environment**
 - OS: [Ubuntu 24]

**Installation method**
- [YES] Docker
**Additional context**
Hi I am running rekono on docker and I am having this issue after getting the vulnerability it seems that metasploit is ignoring the CVE due to an additional quotation:

**Comment by pablosnt** [comment]
Thank you very much for reporting! I have just merged the fix in `develop` branch, so I close this issue. The fix will be included in the next release that will be published during this week I hope

**Comment by phoenixml** [comment]
Thank you so much @pablosnt for taking care of it appreciated.
