### ISSUE TITLE
Add nuclei to the tool list

### ISSUE THREAD

**Issue by theoricien** [pablosnt/rekono#21]
I think it could be great to add nuclei (https://github.com/projectdiscovery/nuclei)
We could also add the feature to link nuclei to local templates to have better results

**Comment by pablosnt** [comment]
Thank you for this proposal! I will take it into account for the next release

**Comment by pablosnt** [comment]
Released in the [latest release 1.4.0](https://github.com/pablosnt/rekono/releases/tag/1.4.0).
