### ISSUE TITLE
Add a group of targets

### ISSUE THREAD

**Issue by theoricien** [pablosnt/rekono#22]
To simplify the process of adding a target to a project it'd be nice to add a group of targets instantly.

**Comment by pablosnt** [comment]
Hi @theoricien, are you talking only about the target address right? Your idea seems good, thank you!

**Comment by theoricien** [comment]
Hi @pablosnt 
Yes, it's about the target address.
For instance my computing system contains a lot of addresses and it may change over time.
-> I need to import a single time all my targets (and maybe delete all of them to replace them over time)

**Comment by pablosnt** [comment]
Included in the version [1.1.0](https://github.com/pablosnt/rekono/releases/tag/1.1.0)
