### ISSUE TITLE
Optimize backend code

### ISSUE THREAD

**Issue by pablosnt** [pablosnt/rekono#222]
- Upgrade `Python`, `Django` and `DRF` to the latest version
- Generic implementation for common features, like `input filters`
- Replace `resources` module by `wordlists`
- Duplicated fields for `ordering` in API
- Try to send email without using `RQ queues`
- Remove deprecated `settings`
- `SMTP` configuration from `Settings` page

**Comment by Rhobar9** [comment]
Your project looks curiously. I would like to tackle the issue. Can I try?

**Comment by pablosnt** [comment]
Hello @Rhobar9, thank you for your proposal! Of course, you can try it if you want. However, my advice is to let me work on the `breaking` issues like this as they require extensive knowledge of Rekono source code.

Moreover, in this case, the issue is a bit unlimited, I mean, I´ve described here some points to do, but I intend to start reviewing the code and optimize, improve, and simplify everything that I can, asking myself if everything could be done in a better or easier way.

One more important thing to take into account here is that this issue and #217 depend on #216.

This is why, in my honest opinion, I would suggest you to start contributing Rekono by working on other issues like #219 or #118 that are better defined and have a very clear definition of done. This kind of issue could be a good opportunity to start contributing and learning how is the source code structured, what components are involved, etc. In addition, if you would like to work on other issues I have a lot of ideas in the backlog that could be a good opportunity for you, for example: adding support for OWASP Amass and Spiderfoot or adding support for custom proxies during the execution of tools.

I hope this message could be useful for you to understand the context of this issue. Thank you again for proposing your contribution. Remember that you can reach me at rekono.project@gmail.com or [Discord](https://discord.gg/Zyduu5C7M3) to solve doubts or discuss development solutions if you finally decide to contribute to Rekono in some way.

Thank you very much!

**Comment by Rhobar9** [comment]
Hello @pablosnt !
Thank you for wide explanation and your open communication. I would like to help you with backend challenges.  Smaller tasks are also fine.
I enjoy long-term collaborations and in future I will handle more issues. However  I would like to focus on one problem on the beginning. Can you assign me #118 issue? 
Kind regards

**Comment by pablosnt** [comment]
Sure! Thank you @Rhobar9 Let me know if I can help you in something

**Comment by Rhobar9** [comment]
Great, thank you @pablosnt .So I start working with this issue.  I created my fork. I need a few days to familiarize myself with the code. When I encounter a problem\doubt, I will contact you via Discord.

**Comment by jgcubillos** [comment]
Hi @pablosnt,
Take a look at this. When I try to install it using Docker, it returns this message. So I don't know how to fix it or maybe change a step.

![imagen](https://github.com/pablosnt/rekono/assets/15838058/d91b3184-e07f-471e-9cdd-1b21139c5414)

Thank you.

**Comment by pablosnt** [comment]
Hi @jgcubillos, did you execute the `docker-compose build` command? It seems to be the reason of your error

**Comment by jgcubillos** [comment]
Yes @pablosnt, I clone the content and execute 
docker-compose build
but show this mesage.

**Comment by pablosnt** [comment]
Okay, this is the problem. You need to update your `docker-compose` version. To be honest, I'm not really sure to what concrete version you must update, but a recent one will be fine. This problem is documented in the next link, as it was a very common problem between the Rekono users: https://github.com/pablosnt/rekono/wiki/FAQ#docker-commands-fail-or-default-credentials-dont-work-for-me
