### ISSUE TITLE
Scan an entire project

### ISSUE THREAD

**Issue by theoricien** [pablosnt/rekono#23]
To simplify the process of scanning multiple targets, it'd be nice to scan all the targets of a single project.
For instance, i'd like to scan the 1000 targets of my project with sslyze

To implement this we could just add 1000 sslyze task to simplify the code
Or, we can use a wordlist parameter if one exist -> need to refactor a little bit the project I think (and how to handle the tools that don't support a wordlist argument)

**Comment by pablosnt** [comment]
I think that we can allow multiple targets selection in the task creation form and request one task for each selected target. Of course, this selector can include a select all option. Thank you!

**Comment by redkris** [comment]
I have managed to install rekono in ubuntu 20.04 using CLI, I am testing the whole scenario the the target local DVWA website but it seems all testing scenario skipped resulted, any ideas ?

**Comment by pablosnt** [comment]
Included in the version [1.1.0](https://github.com/pablosnt/rekono/releases/tag/1.1.0)
