### ISSUE TITLE
Error 401 while Testing the API

### ISSUE THREAD

**Issue by phoenixml** [pablosnt/rekono#248]
Hi Pablo,

I am an API newbie :\ , I passed the api auth and I authorise via token AUTH (apikey)
![image](https://github.com/pablosnt/rekono/assets/14360476/29c5f7f1-c735-4df3-bb06-06a97b98ffd1)

I copied the api key and pass it to the above and login,
when I execute any api request from rekono frontend I am keep getting 401 error:
{
  "detail": "Given token not valid for any token type",
  "code": "token_not_valid",
  "messages": [
    {
      "token_class": "AccessToken",
      "token_type": "access",
      "message": "Token is invalid or expired"
    }
  ]
}

Sorry what I am missing here?

Regards,
Tito

**Comment by pablosnt** [comment]
Hello @phoenixml, you have to generate your API token from your profile, and then, you hace to send it with this header:

Authorization: Token <Your API token>

If you are using the API directly from Swagger, you only have to remember to put the keyword "Token " before your API token value. Let me know if you have any additional problem

**Comment by phoenixml** [comment]
Thank you @pablosnt  for your quick response, yes for now I am trying to test it via Swagger. Correct this is what I am doing:
Generated a token from my profile:
1- 
![image](https://github.com/pablosnt/rekono/assets/14360476/4f75d6e5-4d0e-45eb-b89d-59a69d035c5b)

2- Copy the API token (example:4fc4we4uisn43534jopf345iojkt34)
3- Go to Swagger do authentication

![image](https://github.com/pablosnt/rekono/assets/14360476/e164db8d-07e4-4ea2-bc3d-bc28ad90b066)

in the value field I put:
"Token"4fc4we4uisn43534jopf345iojkt34
and Authorize

I also tried multiple combinations:
"Token4fc4we4uisn43534jopf345iojkt34"
"Token""4fc4we4uisn43534jopf345iojkt34"

 "detail": "Authentication credentials were not provided."

Same error :\

**Comment by pablosnt** [comment]
You are welcome, thank you for all the details. Please, just add a white space between the Token word and the token value, and don't add double quotes to the Token word. Example:

Token abcdefghijklmnopqrstuvwxyz

**Comment by phoenixml** [comment]
yes finally got it working :) 
I will keep that in mind thanks @pablosnt for your help.

**Comment by pablosnt** [comment]
Great! You are welcome :)
