### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by strunz983** [pablosnt/rekono#249]
Hi i need help with rekono
My OS is Linux kali 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
When i try to install rekono-kbx i get this error message  

apt install rekono-kbx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  rekono-kbx
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 101 kB of archives.
After this operation, 136 kB of additional disk space will be used.
Get:1 https://mirrors.netix.net/kali kali-rolling/main amd64 rekono-kbx amd64 1.6.3 [101 kB]
Fetched 101 kB in 1s (120 kB/s)
Selecting previously unselected package rekono-kbx.
(Reading database ... 1063385 files and directories currently installed.)
Preparing to unpack .../rekono-kbx_1.6.3_amd64.deb ...
Unpacking rekono-kbx (1.6.3) ...
dpkg: error processing archive /var/cache/apt/archives/rekono-kbx_1.6.3_amd64.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/16x16/apps/rekono.png', which is also in package kali-menu 2023.4.4
Errors were encountered while processing:
 /var/cache/apt/archives/rekono-kbx_1.6.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Then i download rekono-kbx_1.6.3_amd64.deb and try to install it i get this

dpkg -i rekono-kbx_1.6.3_amd64.deb      
Selecting previously unselected package rekono.
(Reading database ... 1063385 files and directories currently installed.)
Preparing to unpack rekono-kbx_1.6.3_amd64.deb ...
Unpacking rekono (1.6.3) ...
dpkg: error processing archive rekono-kbx_1.6.3_amd64.deb (--install):
 trying to overwrite '/usr/share/icons/hicolor/16x16/apps/rekono.png', which is also in package kali-menu 2023.4.4
Processing triggers for kali-menu (2023.4.4) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 rekono-kbx_1.6.3_amd64.deb

And when i try to --force-overwrite i got this
dpkg --force-overwrite -i rekono-kbx_1.6.3_amd64.deb
(Reading database ... 1063385 files and directories currently installed.)
Preparing to unpack rekono-kbx_1.6.3_amd64.deb ...
Unpacking rekono (1.6.3) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/icons/hicolor/16x16/apps/rekono.png', which is also in package kali-menu 2023.4.4
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/icons/hicolor/256x256/apps/rekono.png', which is also in package kali-menu 2023.4.4
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/icons/hicolor/32x32/apps/rekono.png', which is also in package kali-menu 2023.4.4
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/icons/hicolor/48x48/apps/rekono.png', which is also in package kali-menu 2023.4.4
Setting up rekono (1.6.3) ...
Preparing rekono
Pulling registry.hub.docker.com/pablosnt/rekono:1.6.3 image from registry

And stay like this i need to press Ctrl and c to stop the process
Thank you :)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Installation method**
- [ ] Docker
- [ ] DEB package
- [ ] From Source

**Additional context**

**Comment by pablosnt** [comment]
Hello @strunz983! Thanks for trying to install Rekono

`rekono-kbx` is based on a Docker image, so the message `Pulling registry.hub.docker.com/pablosnt/rekono:1.6.3 image from registry` is normal, and you would need to wait until it finishes (I'm sorry for the inconvenience).

Regarding the previous errors, I've never seen them, but are you trying to install Rekono with `sudo`? I think `apt` shouldn't find any problem overriding files using `sudo`.

If you are already using `sudo`, I would check if this `rekono.png` file already exists in your system. If it exists, you can try to remove it to avoid the overriding error, and then retry the installation.

I'm sorry, I would like to be more useful but as I said I've never seen this error before, and the `apt` installation works for me. Let me know if my solutions work for you or not, and I hope you like Rekono when you finally install it :)

**Comment by strunz983** [comment]
Hi i just install rekono like that 
dpkg --force-all -i rekono-kbx_1.6.3_amd64.deb
Now is OK
Thank you for your  help :)
