### ISSUE TITLE
Scan a Network Block

### ISSUE THREAD

**Issue by jes009** [pablosnt/rekono#26]
Hello

It would be a good idea to scan a full network range for example a /24 , this would make a quality leap to the tool as it could automate finding a network’s weak point.

I don’t really know much about programming other than basic scripting, but I know from the nature of the tools that it’s going to take time, as you’ll have to restructure the way it works today.

By the way, how can we help you provide the tool?

Thanks

**Comment by pablosnt** [comment]
Hello @jes009

This feature is already available. You can create a target with a network address (for example, 10.10.10.0/24) and then execute a process that includes the nmap tool to identify hosts, ports and services in that network. The following steps of the process will use the results of nmap as input. Moreover, you can create targets with IP ranges like 10.10.10.1-10 to scan only some hosts from the network.

Please, let me know if it doesn't work for you. By the time, I close this issue. Thank you!
