### ISSUE TITLE
Rekono seems cannot connect to DB

### ISSUE THREAD

**Issue by dennisarriola** [pablosnt/rekono#310]
Hello,

Good day!

It's me again, having trouble using Rekono.

So it's been a while since the last time I used rekono in my test pc.
I wanted to check the test results from my previous scan, however, after I run it (in the usual way) I cannot login.
I checked the logs and it seems that rekono is not connected to DB.
Kindly see screenshots below:
![image](https://github.com/pablosnt/rekono/assets/54200801/c2daeacc-ff74-4b11-9551-7586f6a50b0e)
I also attached the log, kindly check it as well.
Logs: [rekono_error_log.txt](https://github.com/pablosnt/rekono/files/15102666/rekono_error_log.txt)

I tried all solutions I found in the internet but still NG.

Thank you very much in advance.

**Comment by pablosnt** [comment]
Hello @dennisarriola

What Rekono version are you using right now?

I guess 1.6.5, there is an error in updates from 1.6.4 to 1.6.5. 1.6.5 works but not if you have updated from 1.6.4.

I'm already working in the fix that I hope to release soon. This fix would solve the problem, so you would be able to upgrade to the new 1.6.6 and everything would work.

I will keep you updated
Thanks for the report and my apologies for the inconvenience

**Comment by pablosnt** [comment]
Hello @dennisarriola !

The fix has been released, but it may take some time to get it available in Kali Linux via `apt upgrade rekono-kbx`. However, you can execute one of the following two options to upgrade to the new version in the meantime:

- `apt remove rekono-kbx && apt install rekono-kbx`: data won't be removed by the `apt remove` command and it will be kept at `$HOME/.local/share/rekono`.
- `docker pull pablosnt/rekono:1.6.6 && docker tag pablosnt/rekono:1.6.6 kaboxer/rekono:1.6.6 && docker tag pablosnt/rekono:1.6.6 kaboxer/rekono:current` (you can remove Docker image `pablosnt/rekono:1.6.5` if you want)

After executing one of those two options, you can execute `rekono` command again and the app should work as usual without losing data. Kali package's version will be 1.6.5 until they release the new one (it usually takes some days/weeks), but you would be using the new version 1.6.6 anyway.

**Comment by dennisarriola** [comment]
Hello @pablosnt,

Thank you so much for your support!

I confirm, it is now fixed.
I followed your suggestion to perform `apt remove rekono-kbx && apt install rekono-kbx`

Thanks again!
