### ISSUE TITLE
Work on Mac OSX Apple Silicon Arch

### ISSUE THREAD

**Issue by MrPWH** [pablosnt/rekono#317]
Hi ,
i try install every arch linux but i can't run this 
i think we need it on mac 
thank you for run this project

**Comment by pablosnt** [comment]
Hi,

Today I've been able to execute Rekono with `docker-compose` on Mac M1 with no problems. To be honest, yesterday I got issues, but today it just worked with no changes. Errors are sensible, given that Rekono wasn´t developed on or for that architecture. Could you retry and send me the output where you get the error?

Additionally, in order to reproduce your error, are you running Docker Desktop or just Docker CLI with Docker engine? Could you share your current version of Docker and Docker Compose?

Just FYI, the Docker environment where I got no errors was [this](https://medium.com/@damasamirulkarim/how-i-use-docker-without-docker-desktop-on-macos-df251dae3b81), including also the installation of `docker-compose` with Homebrew.

Thank you in advance!

**Comment by MrPWH** [comment]
> Hi,
> 
> Today I've been able to execute Rekono with `docker-compose` on Mac M1 with no problems. To be honest, yesterday I got issues, but today it just worked with no changes. Errors are sensible, given that Rekono wasn´t developed on or for that architecture. Could you retry and send me the output where you get the error?
> 
> Additionally, in order to reproduce your error, are you running Docker Desktop or just Docker CLI with Docker engine? Could you share your current version of Docker and Docker Compose?
> 
> Just FYI, the Docker environment where I got no errors was [this](https://medium.com/@damasamirulkarim/how-i-use-docker-without-docker-desktop-on-macos-df251dae3b81), including also the installation of `docker-compose` with Homebrew.
> 
> Thank you in advance!

can you make an installations help for this?

**Comment by MrPWH** [comment]
@pablosnt 
<img width="1439" alt="err1" src="https://github.com/user-attachments/assets/de7a446d-980c-4298-b9b9-b2508a1bfb4f">
i have this error when start it

**Comment by pablosnt** [comment]
Oh okay, you can't use that image from MacOS. I'm sorry, maybe it's not clear on the docs.

That image is the one used under the hood by the Desktop application for Kali Linux. For running Rekono on MacOS you must use `docker-compose` alternative. You can check the documentation about it here: https://github.com/pablosnt/rekono/wiki/Installation#docker

Anyway, as I said before, it may not work on Mac M1 given that these images were not created for this arch. So, please, if you can, try it and just let me know if you get any error during the process

I hope this to be useful, but feel free to ask if you have any question

**Comment by MrPWH** [comment]
i have this problem:
```
mrvictim@Mrvictims-MacBook-Air rekono % brew install docker-compose
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
libgedit-gfls                            oxker
==> New Casks
meta-quest-developer-hub

You have 58 outdated formulae and 3 outdated casks installed.

==> Downloading https://ghcr.io/v2/homebrew/core/docker-compose/manifests/2.29.1
######################################################################### 100.0%
==> Fetching docker-compose
==> Downloading https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:00b
######################################################################### 100.0%
==> Pouring docker-compose--2.29.1.arm64_sonoma.bottle.tar.gz
==> Caveats
Compose is a Docker plugin. For Docker to find the plugin, add "cliPluginsExtraDirs" to ~/.docker/config.json:
  "cliPluginsExtraDirs": [
      "/opt/homebrew/lib/docker/cli-plugins"
  ]
==> Summary
🍺  /opt/homebrew/Cellar/docker-compose/2.29.1: 8 files, 52.3MB
==> Running `brew cleanup docker-compose`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
mrvictim@Mrvictims-MacBook-Air rekono % docker-compose build     
[+] Building 0.0s (0/0)                                                         
open /Users/mrvictim/.docker/buildx/current: permission denied
mrvictim@Mrvictims-MacBook-Air rekono % sudo docker-compose build  
Password:
WARN[0000] /Users/mrvictim/Desktop/Private Bug Bounty/Tools/rekono/rekono/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Building 1.0s (6/9)                                    docker:desktop-linux
[+] Building 1.1s (9/9) FINISHED                           docker:desktop-linux
 => [frontend internal] load build definition from Dockerfile.frontend     0.0s
 => => transferring dockerfile: 559B                                       0.0s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 283B                                          0.0s
 => ERROR [frontend internal] load metadata for docker.io/library/node:19  1.1s
 => [backend internal] load build definition from Dockerfile.backend       0.0s
 => => transferring dockerfile: 789B                                       0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 283B                                          0.0s
 => CANCELED [backend internal] load metadata for docker.io/library/pytho  1.1s
 => [executions-worker internal] load .dockerignore                        0.0s
 => => transferring context: 283B                                          0.0s
 => [executions-worker internal] load build definition from Dockerfile.ka  0.0s
 => => transferring dockerfile: 1.63kB                                     0.0s
 => CANCELED [executions-worker internal] load metadata for docker.io/kal  1.1st
------
 > [frontend internal] load metadata for docker.io/library/node:19.6.1-alpine:
------
failed to solve: node:19.6.1-alpine: error getting credentials - err: exit status 1, out: ``
mrvictim@Mrvictims-MacBook-Air rekono % sudo docker login        
2024/08/04 00:04:49 must use ASL logging (which requires CGO) if running as root
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: mvictim1337@gmail.com
Password: 
2024/08/04 00:05:43 must use ASL logging (which requires CGO) if running as root
Error saving credentials: error storing credentials - err: exit status 1, out: ``
mrvictim@Mrvictims-MacBook-Air rekono % 
```




Solved this problem:
`sudo chown -R $(whoami) ~/.docker
`

**Comment by pablosnt** [comment]
So, is it working now? Thanks for the details

**Comment by MrPWH** [comment]
Not working ...

**Comment by pablosnt** [comment]
What was the error after the `docker login`?

You shouldn't need to log in Docker Hub to pull images from the registry. These images exist so you should be able to pull them, for example: https://hub.docker.com/layers/library/node/19.6.1-alpine/images/sha256-64b0af3059f2471184168d366aa5a9fbad9c29e104e87e35336d03e409a27623

Please, can you provide more details about the error? Thanks in advance!

PS: I'm sorry for the late answer, I was on holidays

**Comment by pablosnt** [comment]
I'm closing this issue as its working for me. If the error persists, please, provide me more details about the error you are getting and your environment. I will be happy to help. Thank you for reporting it!
