### ISSUE TITLE
ParrotOS 6.2 installation don't work, docker or deb (no kaboxer)

### ISSUE THREAD

**Issue by zinwelzl** [pablosnt/rekono#321]
this don't work, no kaboxer
wget https://github.com/pablosnt/rekono/releases/download/1.6.6/rekono-kbx_1.6.6_amd64.deb && dpkg -i rekono-kbx_1.6.6_amd64.deb || apt -f install -y

docker-compose build
docker-compose up -d --scale executions-worker=5
empty page https://127.0.0.1/

**Comment by pablosnt** [comment]
Hi,

Kaboxer is a Kali Linux technology that allows to create Desktop applications based on a Docker image. However, ParrotSec doesn't distribute the Kali packages through their APT repositories (of course), and they don't have any similar technology, so I can't create a Parrot package as I did for Kali.

So, the only way to run the Kali Desktop app in Parrot OS is adding Kali Linux APT repository to your Parrot OS system. I did it with the following commands:

```bash
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware" | tee -a /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED444FF07D8D0BF6
apt update
```

After that, you can install the DEB file as stated in the README, or even, you can try to install `rekono-kbx` directly with apt, as it will find and install it from the Kali Linux repository as if you were in Kali.

I hope this to be enough to make it work in ParrotOS, but anyway, if you find some problem during the process, just let me know.
I will update the README to clarify it, as it's very confusing.  Thank you for reporting it!
