### ISSUE TITLE
Is it possible to see the devices affected in /24 o any network block by a particular vulnerability?

### ISSUE THREAD

**Issue by jes009** [pablosnt/rekono#38]
Hi sorry for my last question

Now I have an enhancement idea 

When I scan for example a /24 in the results I see the vulnerabilities but not in what hosts are affected

![image](https://user-images.githubusercontent.com/57327491/189336487-fd90ea17-8144-41fe-b26d-093f208b3e8b.png)

Thanks for your work

**Comment by pablosnt** [comment]
Hi @jes009, thank you for your idea. To do that, you can't filter by vulnerabilities. You have to click over a host, then over a port and the platform will show you the vulnerabilities (and the other findings) related to that host and port dynamically. Did you check that?

**Comment by jes009** [comment]
I think I don't have this possibility because a network is the only asset and not is possible to view one by one

![image](https://user-images.githubusercontent.com/57327491/189343341-7e4ef500-0a43-4db1-9085-52a9f6322747.png)

**Comment by pablosnt** [comment]
Yes, but I guess that your vulnerabilities are found with a process that includes Nmap. So, Nmap will create a host finding for each host up in the network. In the Findings tabs, without filter by any finding type, you can click over the host you want to check, and the related findings will appear.

**Comment by jes009** [comment]
Okay, thanks for your help I can now see the host affected

**Comment by pablosnt** [comment]
You are welcome!
