### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by ablito19** [pablosnt/rekono#68]
Hello
can i change port of 127.0.0.1 like 5500. Another service are already running in default ip. i am using docker version.
thank you

**Comment by pablosnt** [comment]
Hi @ablito19, you can change the port for Docker environment in the following lines:

- Ports exposed by Docker: https://github.com/pablosnt/rekono/blob/main/docker-compose.yml#L266
- Ports configured in Nginx: https://github.com/pablosnt/rekono/blob/main/docker/nginx/nginx.conf#L18 and https://github.com/pablosnt/rekono/blob/main/docker/nginx/nginx.conf#L29

Let me know if you have any problem during the configuration change

**Comment by ablito19** [comment]
hi @pablosnt  it's not working. I got 400 Bad Request. Can you explain more please

**Comment by pablosnt** [comment]
I'm sorry but it should work with this changes. Even it should be enough with changing the por mapping here: https://github.com/pablosnt/rekono/blob/main/docker-compose.yml#L256. In these way, the container will use the ports 80 and 443 internally, and these ports will be accesible in those what you choose im your local host.

Could you tell me what changes did you do?

**Comment by ablito19** [comment]
I make this changes : 

*Ports exposed by Docker: https://github.com/pablosnt/rekono/blob/main/docker-compose.yml#L266
*Ports configured in Nginx: https://github.com/pablosnt/rekono/blob/main/docker/nginx/nginx.conf#L18 *https://github.com/pablosnt/rekono/blob/main/docker/nginx/nginx.conf#L29

can you put the necessary modifications to the files that I could use

**Comment by pablosnt** [comment]
Yes of course. It's easy:

1. Change the port mapping in the `docker-compose.yml` file. Note that you don't need to rebuild the images, just execute `docker-compose up -d` after making the change:
<img width="501" alt="Captura de pantalla 2023-03-04 a las 17 25 09" src="https://user-images.githubusercontent.com/69458381/222917408-b5542b5a-358c-496c-9aa8-d8fa803bbeb2.png">

2. Go to https://localhost:5500 in your browser:
<img width="1552" alt="Captura de pantalla 2023-03-04 a las 17 25 16" src="https://user-images.githubusercontent.com/69458381/222917416-3d45b95c-e0e6-461e-a897-68674c838866.png">

**Comment by ablito19** [comment]
ok i'm try it. Thank you so much

**Comment by ablito19** [comment]
It's work very well. Thank you so much
